language: "python"

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"

script:
    - "pip install --upgrade coveralls flake8"
    - "flake8 ."
    - "coverage run -m unittest discover"
    - "pip install redis==3.4.1"
    - "coverage run -m unittest discover"

services:
    - "redis-server"

deploy:
  provider: "pypi"
  user: "honzajavorek"
  password:
    secure: "NLHLE9kVASnibrSDckdt1lmf8CfnKevmpCgAkrg2R+ajxlz3iNRfdKhSxJhExC+VMYryLBGOoeOrV+HwkZv2Lo3LlCstmh7y8k/AKp1v02xZvaOtD4w37eI23JwpNA/yXm/IZqy96cxHd4PdX6pul7xKoFRUj6Mc0PVWe+/izWg="
  on:
    python: "3.6"
    tags: true
    repo: "honzajavorek/redis-collections"
    distributions: "sdist bdist_wheel"

notifications:
  email: false

after_success:
    - "coveralls"
